import os
import json
import asyncio
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from google import genai
from google.genai import types as genai_types
from schemas.copilot import CopilotRequest
import logging
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/copilot", tags=["Copilot"])

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")


SYSTEM_PROMPT = """You are OpsTwin AI Workflow Copilot.

You are NOT a generic chatbot.

You are an enterprise Business Process Intelligence expert.

You help organizations understand, optimize and automate workflows.

You always answer using structured workflow intelligence generated by the platform.

You have access to:
- extracted document
- workflow graph
- entities
- actors
- departments
- systems
- workflow metrics
- bottlenecks
- optimization suggestions
- compliance analysis
- ROI estimation

Never summarize the uploaded document unless explicitly requested.

Always explain business impact.

Always provide actionable recommendations.

Use professional markdown formatting.
Use headings.
Use bullet points.
Keep responses concise but insightful.

Before generating a response, classify the user's intent to route to the correct data source (e.g., Workflow Explanation, Bottleneck Analysis, Cost Savings, etc.).

Every answer should include:
1. Direct answer
2. Business Impact
3. AI Recommendation
4. Estimated Improvement (if applicable)
5. Confidence Score

Interactive Recommendations: If you recommend modifying the workflow (e.g., merging steps, removing a step, or automating a step), you MUST include a special action tag at the end of your recommendation block so the UI can render an interactive button.
Action tags format:
[APPLY_MERGE:Step_ID_1,Step_ID_2]
[APPLY_REMOVE:Step_ID]
[APPLY_AUTOMATE:Step_ID]

ERROR HANDLING:
If you cannot answer based on the structured context, NEVER say "I don't know." Instead respond: "I couldn't find enough workflow intelligence for that question. Based on the available workflow, here are the closest insights..."
"""

def build_prompt(request: CopilotRequest) -> str:
    wf = request.workflow or {}
    opt = request.optimization or {}
    
    # Extract actors, departments, systems
    steps = wf.get('steps', [])
    actors = list(set(s.get('role') for s in steps if s.get('role')))
    departments = list(set(s.get('department') for s in steps if s.get('department')))
    systems = list(set(s.get('system') for s in steps if s.get('system')))
    
    structured_context = {
        "workflow": wf,
        "workflowMetrics": {
            "current_steps": opt.get('current_steps'),
            "optimized_steps": opt.get('optimized_steps'),
            "automation_score": opt.get('automation_score')
        },
        "bottlenecks": opt.get('removed_steps', []),
        "optimization": opt.get('automation_candidates', []),
        "roi": {
            "estimated_time_saved": opt.get('estimated_time_saved'),
            "estimated_cost_saved": opt.get('estimated_cost_saved')
        },
        "actors": actors,
        "departments": departments,
        "systems": systems
    }
    
    if request.document_text:
        # truncate doc text to prevent blowing up context
        structured_context["documentSummary"] = request.document_text[:8000]

    context_json = json.dumps(structured_context, indent=2)

    # Conversation History
    history = []
    for msg in request.messages:
        role = "User" if msg.role == "user" else "Assistant"
        history.append(f"{role}: {msg.content}")
        
    history_str = "\n\n".join(history)
    
    full_prompt = f"{SYSTEM_PROMPT}\n\n--- STRUCTURED CONTEXT ---\n{context_json}\n\n--- CONVERSATION HISTORY ---\n{history_str}\n\nAssistant:"
    return full_prompt

@router.post("/chat")
async def chat_stream(request: CopilotRequest):
    gemini_ok = bool(GEMINI_API_KEY and GEMINI_API_KEY != "your-gemini-api-key-here")
    groq_ok = bool(GROQ_API_KEY and GROQ_API_KEY != "your-groq-api-key-here")
    openai_ok = bool(OPENAI_API_KEY and OPENAI_API_KEY != "your-openai-api-key-here")
    
    if not gemini_ok and not groq_ok and not openai_ok:
        raise HTTPException(status_code=500, detail="No AI provider configured.")

    prompt = build_prompt(request)
    
    async def generate():
        # Try OpenAI First if available
        if openai_ok:
            try:
                from openai import AsyncOpenAI
                openai_client = AsyncOpenAI(api_key=OPENAI_API_KEY)
                stream = await openai_client.chat.completions.create(
                    model=OPENAI_MODEL,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3,
                    max_tokens=4096,
                    stream=True,
                )
                async for chunk in stream:
                    content = chunk.choices[0].delta.content
                    if content:
                        yield f"data: {json.dumps({'content': content})}\n\n"
                        await asyncio.sleep(0.01)
                yield "data: [DONE]\n\n"
                return
            except Exception as openai_e:
                err_str = str(openai_e)
                is_transient = any(x in err_str.lower() for x in ("503", "unavailable", "429", "rate_limit", "quota"))
                if is_transient and (gemini_ok or groq_ok):
                    logger.warning("OpenAI unavailable for copilot - Switching to next provider")
                else:
                    logger.exception("Error in Copilot OpenAI streaming.")
                    yield f"data: {json.dumps({'error': err_str})}\n\n"
                    return

        # Try Gemini
        if gemini_ok:
            try:
                client = genai.Client(api_key=GEMINI_API_KEY)
                response = client.models.generate_content_stream(
                    model=GEMINI_MODEL,
                    contents=prompt,
                    config=genai_types.GenerateContentConfig(temperature=0.3, max_output_tokens=4096),
                )
                for chunk in response:
                    if chunk.text:
                        yield f"data: {json.dumps({'content': chunk.text})}\n\n"
                        await asyncio.sleep(0.01)
                yield "data: [DONE]\n\n"
                return
            except Exception as e:
                err_str = str(e)
                is_transient = any(x in err_str for x in ("503", "UNAVAILABLE", "429", "RESOURCE_EXHAUSTED", "quota"))
                if is_transient and groq_ok:
                    logger.warning("Gemini unavailable for copilot - Switching to Groq")
                else:
                    logger.exception("Error in Copilot streaming.")
                    yield f"data: {json.dumps({'error': err_str})}\n\n"
                    return
        
        # Try Groq
        if groq_ok:
            try:
                from groq import AsyncGroq
                groq_client = AsyncGroq(api_key=GROQ_API_KEY)
                stream = await groq_client.chat.completions.create(
                    model=GROQ_MODEL,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3,
                    max_tokens=4096,
                    stream=True,
                )
                async for chunk in stream:
                    content = chunk.choices[0].delta.content
                    if content:
                        yield f"data: {json.dumps({'content': content})}\n\n"
                        await asyncio.sleep(0.01)
                yield "data: [DONE]\n\n"
            except Exception as groq_e:
                logger.exception("Error in Copilot Groq streaming.")
                yield f"data: {json.dumps({'error': str(groq_e)})}\n\n"
            
    return StreamingResponse(generate(), media_type="text/event-stream")


